package ru.example.recipeapp

object Constants {
    const val ARG_CATEGORY_ID = "ARG_CATEGORY_ID"
    const val ARG_CATEGORY_NAME = "ARG_CATEGORY_NAME"
    const val ARG_CATEGORY_IMAGE_URL = "ARG_CATEGORY_IMAGE_URL"

    const val ARG_RECIPE_ID = "ARG_RECIPE_ID"
    const val ARG_RECIPE_NAME = "ARG_RECIPE_NAME"
    const val ARG_RECIPE_IMAGE_URL = "ARG_RECIPE_IMAGE_URL"
    const val ARG_RECIPE_METHOD = "ARG_RECIPE_METHOD"
    const val ARG_RECIPE_INGREDIENTS = "ARG_RECIPE_INGREDIENTS"
}